image: node:latest

cache:
  paths:
    - node_modules/

stages:
    - build

build:
    stage: build
    tags:
        - docker
    script:
        - echo "Build started"
        - npm install
        - npm run lint
        - npm run serve
        - echo "Build complete"